<?php // This file is automatically generated. Do not edit.

$tsvshop['CatRoot']=7;
$tsvshop['DisplayNotice']='true';
$tsvshop['MinimumOrder']='';
$tsvshop['MonetarySymbol']=' грн.';
$tsvshop['PriceFormat']='0,00';
$tsvshop['SecFields']='fio,adress,city,phone,email';
$tsvshop['SecPassword']='MyPass';
$tsvshop['SmtpFromEmail']='my@mail.com';
$tsvshop['SmtpFromName']='Интернет-магазин';
$tsvshop['SmtpReplyEmail']='my@mail.com';
$tsvshop['StatusOrder']='Новый==d4e8f1||Ожидание оплаты==feecd8||Оплачено==e7f0db||Завершено==e4f0c6||Отменен==fce3e2';
$tsvshop['SubjectMailAdmin']='Поступил новый заказ';
$tsvshop['SubjectMailUser']='Заказ успешно принят';
$tsvshop['SubjectUpdateStatus']='Изменение статуса заказа';
$tsvshop['TypeCat']='docs';
$tsvshop['addons_addons_active']='yes';
$tsvshop['addons_config_active']='yes';
$tsvshop['addons_sales_active']='yes';
$tsvshop['MySQL_DB']='{DBNAME}';
$tsvshop['MySQL_Pass']='{DBPASS}';
$tsvshop['MySQL_Prefix']='idlq_';
$tsvshop['MySQL_Server']='{DBHOST}';
$tsvshop['MySQL_User']='{DBUSER}';
?>